// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: ecommerce.proto

package bff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EcommerceService_AddUsers_FullMethodName     = "/ecommerce.EcommerceService/AddUsers"
	EcommerceService_UpdateUsers_FullMethodName  = "/ecommerce.EcommerceService/UpdateUsers"
	EcommerceService_DelUsers_FullMethodName     = "/ecommerce.EcommerceService/DelUsers"
	EcommerceService_GetUsersById_FullMethodName = "/ecommerce.EcommerceService/GetUsersById"
	EcommerceService_SearchUsers_FullMethodName  = "/ecommerce.EcommerceService/SearchUsers"
)

// EcommerceServiceClient is the client API for EcommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcommerceServiceClient interface {
	// -----------------------users-----------------------
	AddUsers(ctx context.Context, in *AddUsersReq, opts ...grpc.CallOption) (*AddUsersResp, error)
	UpdateUsers(ctx context.Context, in *UpdateUsersReq, opts ...grpc.CallOption) (*UpdateUsersResp, error)
	DelUsers(ctx context.Context, in *DelUsersReq, opts ...grpc.CallOption) (*DelUsersResp, error)
	GetUsersById(ctx context.Context, in *GetUsersByIdReq, opts ...grpc.CallOption) (*GetUsersByIdResp, error)
	SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersResp, error)
}

type ecommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcommerceServiceClient(cc grpc.ClientConnInterface) EcommerceServiceClient {
	return &ecommerceServiceClient{cc}
}

func (c *ecommerceServiceClient) AddUsers(ctx context.Context, in *AddUsersReq, opts ...grpc.CallOption) (*AddUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUsersResp)
	err := c.cc.Invoke(ctx, EcommerceService_AddUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) UpdateUsers(ctx context.Context, in *UpdateUsersReq, opts ...grpc.CallOption) (*UpdateUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUsersResp)
	err := c.cc.Invoke(ctx, EcommerceService_UpdateUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) DelUsers(ctx context.Context, in *DelUsersReq, opts ...grpc.CallOption) (*DelUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUsersResp)
	err := c.cc.Invoke(ctx, EcommerceService_DelUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) GetUsersById(ctx context.Context, in *GetUsersByIdReq, opts ...grpc.CallOption) (*GetUsersByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersByIdResp)
	err := c.cc.Invoke(ctx, EcommerceService_GetUsersById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResp)
	err := c.cc.Invoke(ctx, EcommerceService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcommerceServiceServer is the server API for EcommerceService service.
// All implementations must embed UnimplementedEcommerceServiceServer
// for forward compatibility
type EcommerceServiceServer interface {
	// -----------------------users-----------------------
	AddUsers(context.Context, *AddUsersReq) (*AddUsersResp, error)
	UpdateUsers(context.Context, *UpdateUsersReq) (*UpdateUsersResp, error)
	DelUsers(context.Context, *DelUsersReq) (*DelUsersResp, error)
	GetUsersById(context.Context, *GetUsersByIdReq) (*GetUsersByIdResp, error)
	SearchUsers(context.Context, *SearchUsersReq) (*SearchUsersResp, error)
	mustEmbedUnimplementedEcommerceServiceServer()
}

// UnimplementedEcommerceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEcommerceServiceServer struct {
}

func (UnimplementedEcommerceServiceServer) AddUsers(context.Context, *AddUsersReq) (*AddUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUsers not implemented")
}
func (UnimplementedEcommerceServiceServer) UpdateUsers(context.Context, *UpdateUsersReq) (*UpdateUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUsers not implemented")
}
func (UnimplementedEcommerceServiceServer) DelUsers(context.Context, *DelUsersReq) (*DelUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUsers not implemented")
}
func (UnimplementedEcommerceServiceServer) GetUsersById(context.Context, *GetUsersByIdReq) (*GetUsersByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersById not implemented")
}
func (UnimplementedEcommerceServiceServer) SearchUsers(context.Context, *SearchUsersReq) (*SearchUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedEcommerceServiceServer) mustEmbedUnimplementedEcommerceServiceServer() {}

// UnsafeEcommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcommerceServiceServer will
// result in compilation errors.
type UnsafeEcommerceServiceServer interface {
	mustEmbedUnimplementedEcommerceServiceServer()
}

func RegisterEcommerceServiceServer(s grpc.ServiceRegistrar, srv EcommerceServiceServer) {
	s.RegisterService(&EcommerceService_ServiceDesc, srv)
}

func _EcommerceService_AddUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).AddUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_AddUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).AddUsers(ctx, req.(*AddUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_UpdateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).UpdateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_UpdateUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).UpdateUsers(ctx, req.(*UpdateUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_DelUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).DelUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_DelUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).DelUsers(ctx, req.(*DelUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_GetUsersById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).GetUsersById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_GetUsersById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).GetUsersById(ctx, req.(*GetUsersByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SearchUsers(ctx, req.(*SearchUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EcommerceService_ServiceDesc is the grpc.ServiceDesc for EcommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.EcommerceService",
	HandlerType: (*EcommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUsers",
			Handler:    _EcommerceService_AddUsers_Handler,
		},
		{
			MethodName: "UpdateUsers",
			Handler:    _EcommerceService_UpdateUsers_Handler,
		},
		{
			MethodName: "DelUsers",
			Handler:    _EcommerceService_DelUsers_Handler,
		},
		{
			MethodName: "GetUsersById",
			Handler:    _EcommerceService_GetUsersById_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _EcommerceService_SearchUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecommerce.proto",
}
